version: "3.6"

services:
  kaspad:
    # allow to automatically build image if not exists upstream
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: docker.io/kaspa/kaspad
    ports:
      # P2P
      - 16111:16111
      # mainnet RPC
      - 16110:16110
      # testnet RPC
      - 16210:16210
      # mainnet borshch RPC
      - 17110:17110
      # testnet borshch RPC
      - 17210:17210
      # mainnet json RPC
      - 18110:18110
      # testnet json RPC
      - 18210:18210

    command: "./kaspad --utxoindex --appdir /app/data"
    # testnet command
    # command: './kaspad --testnet --netsuffix=11 --utxoindex --appdir /app/data'
    volumes:
      - type: volume
        source: data
        target: /app/data

volumes:
  data:
